FROM python:3.11-slim

WORKDIR /app

COPY artifacts/ artifacts/
COPY inference/ inference/

RUN pip install --no-cache-dir \
fastapi \
uvicorn \ 
scikit-learn==1.7.0 \
numpy \
joblib \
&& rm -rf /root/ .cache

# API port
EXPOSE 8000

# Starting fastAPI app
CMD ["uvicorn","inference.app:app","--host","0.0.0.0","--port","8000"]